### ISSUE TITLE
第五步Train the whole model with RL时，没有ids_to_tokens

### ISSUE THREAD

**Issue by yifanjun** [RowitZou/topic-dialog-summ#20]
可能我问了个很蠢的问题，但我确实不知道怎么处理。
在进行第五步训练时，会报错，说 "models/rl.model.py"第499行：
AttributeError: 'collections.OrderedDict' object has no attribute 'ids_to_tokens'
不太明白是不是因为版本原因。除了pytorch是1.9.0+cu111，其他的包我尝试都换成readme中的版本。请问有人遇到过这个问题么？

**Comment by vkmu** [comment]
我的`transformers`版本是4.15.0。通过查看`BertTokenizer`类的`__init__()`源码可知，`ids_to_tokens`不在`vocab`里面。
```python
self.vocab = load_vocab(vocab_file)
self.ids_to_tokens = collections.OrderedDict([(ids, tok) for tok, ids in self.vocab.items()])
```

**Comment by RowitZou** [comment]
> 可能我问了个很蠢的问题，但我确实不知道怎么处理。 在进行第五步训练时，会报错，说 "models/rl.model.py"第499行： AttributeError: 'collections.OrderedDict' object has no attribute 'ids_to_tokens' 不太明白是不是因为版本原因。除了pytorch是1.9.0+cu111，其他的包我尝试都换成readme中的版本。请问有人遇到过这个问题么？

能提供详细的Error Log吗？

**Comment by yifanjun** [comment]
> > 可能我问了个很蠢的问题，但我确实不知道怎么处理。 在进行第五步训练时，会报错，说 "models/rl.model.py"第499行： AttributeError: 'collections.OrderedDict' object has no attribute 'ids_to_tokens' 不太明白是不是因为版本原因。除了pytorch是1.9.0+cu111，其他的包我尝试都换成readme中的版本。请问有人遇到过这个问题么？
> 
> 能提供详细的Error Log吗？

gpu_rank 0
[2022-01-07 13:24:40,472 INFO] * number of parameters: 211432223
[2022-01-07 13:24:40,472 INFO] Start training...
[2022-01-07 13:24:57,550 INFO] Loading train dataset from bert_data/final/csds.train.pt, number of examples: 9101
/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/models/rl_model.py:527: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  topk_beam_index = topk_ids.floor_divide(vocab_size).long()
Traceback (most recent call last):
  File "./src/train.py", line 163, in <module>
    train(args, device_id)
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/train_abstractive.py", line 363, in train
    train_single(args, device_id)
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/train_abstractive.py", line 429, in train_single
    trainer.train(train_iter_fct, args.train_steps)
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/models/rl_model_trainer.py", line 172, in train
    report_stats, step)
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/models/rl_model_trainer.py", line 203, in _gradient_calculation
    rl_loss, decode_output, topic_loss, _, _ = self.model(batch)
  File "/home/user/anaconda3/envs/zouyifan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/models/rl_model.py", line 912, in forward
    topic_vec=topic_vec_ge)
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/models/rl_model.py", line 499, in _fast_translate_batch
    words = [self.vocab.ids_to_tokens[w] for w in words]
  File "/home/user/zouyifan/lab421/CSDS/models/TDS-SATM/src/models/rl_model.py", line 499, in <listcomp>
    words = [self.vocab.ids_to_tokens[w] for w in words]
AttributeError: 'collections.OrderedDict' object has no attribute 'ids_to_tokens'

除去上面的一些初始化信息，这里就是完整的报错。我现在怀疑可能是transformers的版本问题，就如上面那个回答所说一样。

**Comment by yifanjun** [comment]
> 我的`transformers`版本是4.15.0。通过查看`BertTokenizer`类的`__init__()`源码可知，`ids_to_tokens`不在`vocab`里面。
> 
> ```python
> self.vocab = load_vocab(vocab_file)
> self.ids_to_tokens = collections.OrderedDict([(ids, tok) for tok, ids in self.vocab.items()])
> ```

感谢，很有用。下面给出具体方案：
在`src/models/rl_model.py`中，做出以下修改：
1. 开头添加`from nltk import collections`
2. `__inti__()`方法中，在`self.vocab=vocab`之后添加`self.ids_to_tokens=collections.OrderedDict([(ids, tok) for tok, ids in self.vocab.items()])`
3. 第499行，修改为`words = [self.ids_to_tokens[w] for w in words]`
